/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.99
 * Generated at: 2024-04-18 05:30:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1713417489367L));
    _jspx_dependants.put("jar:file:/C:/semi-spring/Asihana/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css\">\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.slim.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        *{\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            color : black;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding : 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .outer{\r\n");
      out.write("            width: 1200px;\r\n");
      out.write("            height: auto;\r\n");
      out.write("            margin : auto;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .main{\r\n");
      out.write("            width : 1000px;\r\n");
      out.write("            margin : auto;\r\n");
      out.write("            margin-bottom : 80px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .searchbar{\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 50px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #searchform{\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #searchtext{\r\n");
      out.write("            border : none;\r\n");
      out.write("            border-radius: 50px;\r\n");
      out.write("            background: none;\r\n");
      out.write("            outline : none;\r\n");
      out.write("            width: 500px;\r\n");
      out.write("            height: 50px;\r\n");
      out.write("            background-color: rgba(239, 239, 238, 0.575);\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #searchbtn{\r\n");
      out.write("            display: none;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .tag{\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 30px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .tag:hover{\r\n");
      out.write("        	cursor : pointer;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .tagbtn{\r\n");
      out.write("            font-size: small;\r\n");
      out.write("            margin-right: 3px;\r\n");
      out.write("            padding : 2px 7px 2px 7px;\r\n");
      out.write("            width: auto;\r\n");
      out.write("            display : inline-block;\r\n");
      out.write("            background-color: #ff595e;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            color : white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .storyBoardView{\r\n");
      out.write("            position : relative;\r\n");
      out.write("            z-index : 0;\r\n");
      out.write("            margin-top: 40px;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 500px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .storyBoardView>img{\r\n");
      out.write("            position : absolute;\r\n");
      out.write("            z-index : 1;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #title{\r\n");
      out.write("            position : absolute;\r\n");
      out.write("            z-index : 2;\r\n");
      out.write("            font-size : large;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            color : white;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            width: auto;\r\n");
      out.write("            margin-left: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #boardTitle{\r\n");
      out.write("            position : absolute;\r\n");
      out.write("            z-index: 5;\r\n");
      out.write("            width: 1000px;\r\n");
      out.write("            color : wheat;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            font-weight: 800;\r\n");
      out.write("            font-size: x-larger;\r\n");
      out.write("            top : 25%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #detail{\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            z-index: 4;\r\n");
      out.write("            left : 90%;\r\n");
      out.write("            bottom : 10%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #storypage{\r\n");
      out.write("            width: auto;\r\n");
      out.write("            background-color: rgba(50, 50, 50, 0.308);\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            color : white;\r\n");
      out.write("            padding : 2px 10px 2px 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .cityView{\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            background-color: #faf3dd;\r\n");
      out.write("            padding-left : 30px;\r\n");
      out.write("        }\r\n");
      out.write("        .city{\r\n");
      out.write("            background-color: white;\r\n");
      out.write("            margin : 20px 0px 20px 0px;\r\n");
      out.write("            width: 225px;\r\n");
      out.write("            height: 300px;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            margin-right: 7px;\r\n");
      out.write("            box-shadow: 1px 1px 5px 2px gray ;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .cityPhoto{\r\n");
      out.write("            margin-top: 5px;\r\n");
      out.write("            margin-left: 5px;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 70%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .cityPhoto>img{\r\n");
      out.write("            width: 95%;\r\n");
      out.write("            height: 95%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .cityName{\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 20%;\r\n");
      out.write("            background-color: white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .cityName>h5{\r\n");
      out.write("            line-height: 30px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            font-weight: 800;\r\n");
      out.write("            margin : 0px;\r\n");
      out.write("        }\r\n");
      out.write("        .cityName>h6{\r\n");
      out.write("            line-height: 40px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            font-weight: 800;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "WEB-INF/views/common/headerbar.jsp", out, false);
      out.write("\r\n");
      out.write("	\r\n");
      out.write("    <div class=\"outer\">\r\n");
      out.write("        <div class=\"main\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"searchbar\">\r\n");
      out.write("                <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">/allSearch.customer\" name=\"search\" id=\"searchform\">\r\n");
      out.write("                    <input type=\"text\" name=\"query\" id=\"searchtext\" placeholder=\"검색어를 입력하세요\">\r\n");
      out.write("                    <button type=\"submit\" id=\"searchbtn\"></button>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"tag\">\r\n");
      out.write("                <div class=\"tagbtn\">#아이와함께</div>\r\n");
      out.write("                <div class=\"tagbtn\">#가족여행</div>\r\n");
      out.write("                <div class=\"tagbtn\">#일본여행</div>\r\n");
      out.write("                <div class=\"tagbtn\">#중국여행</div>\r\n");
      out.write("                <div class=\"tagbtn\">#커플여행</div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"storyBoardView\">\r\n");
      out.write("                <div id=\"title\"> S T O R Y </div>\r\n");
      out.write("                <div id=\"boardTitle\">여행스토리의 제목</div>\r\n");
      out.write("                <img src=\"https://content.skyscnr.com/m/64f1189bc1e2bf0e/original/UK-ST3-165-TRAVELTRENDS-Q323-Article2-1-2.jpg?crop=1224px:647px&position=attention\" alt=\"\">\r\n");
      out.write("                <div id=\"detail\"><a href=\"#\" id=\"storypage\">상세보기 ></a></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <script>\r\n");
      out.write("            	$('.tagbtn').on('click', function(){\r\n");
      out.write("            		let tagbtn = $(this).text().substring(1);\r\n");
      out.write("            		$('#searchtext').val(tagbtn);\r\n");
      out.write("            	})\r\n");
      out.write("\r\n");
      out.write("            </script>\r\n");
      out.write("\r\n");
      out.write("            <br><br><br>\r\n");
      out.write("            <div>\r\n");
      out.write("                <h4>추천여행지</h4>\r\n");
      out.write("            </div>\r\n");
      out.write("            <br>\r\n");
      out.write("            <div class=\"cityView\">\r\n");
      out.write("                <div class=\"city\">\r\n");
      out.write("                    <div class=\"cityPhoto\">\r\n");
      out.write("                        <img src=\"https://tourimage.interpark.com//Spot/187/15599/202112/6377508663314465670.jpg\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"cityName\">\r\n");
      out.write("                        <h5>피렌체</h5>\r\n");
      out.write("                        <h6>이탈리아</h6>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"city\">\r\n");
      out.write("                    <div class=\"cityPhoto\">\r\n");
      out.write("                        <img src=\"https://ak-d.tripcdn.com/images/1i6192224syebo5lcFD0D_W_400_0_R5_Q90.jpg?proc=source/trip\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"cityName\">\r\n");
      out.write("                        <h5>도쿄</h5>\r\n");
      out.write("                        <h6>일본</h6>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"city\">\r\n");
      out.write("                    <div class=\"cityPhoto\">\r\n");
      out.write("                        <img src=\"https://mblogthumb-phinf.pstatic.net/MjAxNjEyMDZfMjc2/MDAxNDgwOTUzMzQ2NDMy.XZTVP0zjye6zsCzTNFiRM72yprWmzNRuF_yrZvYRD8cg.r-VzTAWxS9qAxdpTcXcNdWIUPoc0MlwQdMFswLi1O5Qg.JPEG.minzsnap/IMG_3725.JPG?type=w420\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"cityName\">\r\n");
      out.write("                        <h5>어디지</h5>\r\n");
      out.write("                        <h6>스위스</h6>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"city\">\r\n");
      out.write("                    <div class=\"cityPhoto\">\r\n");
      out.write("                        <img src=\"https://st3.depositphotos.com/22201120/37041/i/1600/depositphotos_370410358-stock-photo-jinbi-square-golden-horse-jade.jpg\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"cityName\">\r\n");
      out.write("                        <h5>아마</h5>\r\n");
      out.write("                        <h6>중국</h6>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>   \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "WEB-INF/views/common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>   \r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
